updateBranch: true
deleteBranchAfterMerge: true
reportStatus: true
mergeMethod: squash
minApprovals:
  COLLABORATOR: 0
maxRequestedChanges:
  NONE: 0
blockingLabels:
  - blocked
rules:
  - requiredLabels:
      - automerge
mergeCommitMessage: "{title} (#{number})"
