main: io.github.portlek.fakeplayer.FakePlayer
name: ${project.name}
version: ${project.version}
description: ${project.description}
api-version: '1.13'
authors:
  - portlek
commands:
  fakeplayer:
    description: Main command of the plugin.
    permission: fakeplayer.command.main
    permission-message: You don't have permission!
    usage: /<command> [help|version|reload|menu]
    aliases:
      - fp
permissions:
  fakeplayer.*:
    description: Allows you to access to the all plugin.
    children:
      fakeplayer.version: true
      fakeplayer.command.*: true
  fakeplayer.command.*:
    description: It allows you to use to all commands of the plugin.
    children:
      fakeplayer.command.main: true
      fakeplayer.command.help: true
      fakeplayer.command.reload: true
      fakeplayer.command.version: true
      fakeplayer.command.menu: true
      fakeplayer.command.add: true
      fakeplayer.command.remove: true
      fakeplayer.command.toggle: true
      fakeplayer.command.chat: true
  fakeplayer.version:
    description: It allows you to notify if there is new update for the plugin on join.
  fakeplayer.command.main:
    description: It allows you to use to /fakeplayer command.
    default: 'true'
  fakeplayer.command.help:
    description: It allows you to use to /fakeplayer help command.
    default: 'true'
  fakeplayer.command.reload:
    description: It allows you to use to /fakeplayer reload command.
  fakeplayer.command.version:
    description: It allows you to use to /fakeplayer version command.
  fakeplayer.command.menu:
    description: It allows you to use to /fakeplayer menu command.
  fakeplayer.command.add:
    description: It allows you to use to /fakeplayer add <name> command.
  fakeplayer.command.remove:
    description: It allows you to use to /fakeplayer remove <name> command.
  fakeplayer.command.toggle:
    description: It allows you to use to /fakeplayer toggle <name> command.
  fakeplayer.command.tp:
    description: It allows you to use to /fakeplayer tp <name> command.
  fakeplayer.command.chat:
    description: It allows you to use to /fakeplayer chat <name> <message> command.
