name: Snapshot Release

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Snapshot Release
    runs-on: ubuntu-latest
    if: "github.event.release.prerelease"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradlew-

      - uses: crazy-max/ghaction-import-gpg@v5.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - run: |
          chmod +x gradlew
          ./gradlew build

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            plugin/build/libs/FakePlayerPlugin.jar
